import { z } from 'zod';

export const motorizedSpecSchema = z.object({
  brand: z.string().min(1),
  model: z.string().min(1),
  year: z.number().int().min(1900).max(new Date().getFullYear()),
  serialNumber: z.string().optional(),
  enginePower: z.number().optional(),
  enginePowerKw: z.number().optional(),
  engineModel: z.string().optional(),
  fuelType: z.enum(['DIESEL', 'GASOLINE', 'ELECTRIC', 'HYBRID', 'GAS']).optional(),
  fuelCapacity: z.number().optional(),
  transmission: z.enum(['MANUAL', 'AUTOMATIC', 'HYDROSTATIC', 'CVT']).optional(),
  numberOfGears: z.number().optional(),
  length: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  weight: z.number().optional(),
  wheelbase: z.number().optional(),
  groundClearance: z.number().optional(),
  workingWidth: z.number().optional(),
  capacity: z.number().optional(),
  liftCapacity: z.number().optional(),
  threePtHitch: z.boolean().optional(),
  pto: z.boolean().optional(),
  ptoSpeed: z.string().optional(),
  frontAxle: z.string().optional(),
  rearAxle: z.string().optional(),
  frontTireSize: z.string().optional(),
  rearTireSize: z.string().optional(),
  hydraulicFlow: z.number().optional(),
  hydraulicPressure: z.number().optional(),
  grainTankCapacity: z.number().optional(),
  headerWidth: z.number().optional(),
  threshingWidth: z.number().optional(),
  cleaningArea: z.number().optional(),
  engineHours: z.number().optional(),
  mileage: z.number().optional(),
  lastServiceDate: z.string().optional(),
  nextServiceDate: z.string().optional(),
  isOperational: z.boolean().optional(),
  images: z.array(z.string()).optional(),
  description: z.string().optional(),
  price: z.number().optional(),
  currency: z.string().optional(),
});